blabla/blabla/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from blabla import views as core_views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', core_views.MapFormView.as_view()),
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', auth_views.login,
        {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,
        {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
]

blabla/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from registration import views as registration_views
from blabla.blabla import views as core_views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^add_routes/$', core_views.MapFormView.as_view(), name='add_routes'),
    url(r'^search_routes/$', core_views.SearchFormView.as_view(), name='search_routes'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^view_routes/$', core_views.view_routes, name='view_routes'),
    url(r'^view_signed_routes/$', core_views.view_signed_routes, name='view_signed_routes'),
    url(r'^(?P<object_id>[0-9]+)/delete_route/$', core_views.delete_route, name='delete_route'),
    url(r'^(?P<route_id>(\d+))/(?P<signed_id>(\d+))/sign_off_route/$', core_views.sign_off_route, name='sign_off_route'),
    url(r'^login/$', auth_views.login,
        {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,
        {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^signup/$', registration_views.signup, name='signup'),
]

blabla/blabla/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.db.models.fields import FloatField, DateField, IntegerField
from django_google_maps import fields as map_fields
from django.contrib.auth.models import User
from datetime import datetime

class MapModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    passengers_number = IntegerField(default=1)
    passengers_signed = IntegerField(default=0)
    price = FloatField(default=0.0)
    date = DateField(default=datetime.now())
    hour = IntegerField(default=12)
    address_start = map_fields.AddressField(max_length=500)
    address_end = map_fields.AddressField(max_length=500)
    address_start_lat = FloatField()
    address_start_lng = FloatField()
    address_end_lat = FloatField()
    address_end_lng = FloatField()
    waypoints = JSONField()

class SearchModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    route_id = models.ManyToManyField('MapModel')
    # address_start = map_fields.AddressField(max_length=500)
    # address_end = map_fields.AddressField(max_length=500)
    # address_start_lat = FloatField()
    # address_start_lng = FloatField()
    # address_end_lat = FloatField()
    # address_end_lng = FloatField()

templates/add_routes.html
{% extends 'base.html' %} {% block title %}Login{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="id_passengers_number">Passengers number:</label>
                    <input class="form-control" type="number" name="passengers_number" max=5 value="1" required id="id_passengers_number"/>

                    <label for="id_price">Price:</label>
                    <input class="form-control" type="number" name="price" min=0 value="0.0" required id="id_price"/>

                    <label for="id_date">Date:</label>
                    <input class="form-control" type="date" name="date" required id="id_date"/>

                    <label for="id_hour">Hour:</label>
                    <input class="form-control" type="number" name="hour" value="12" required id="id_hour"/>

                   <label for="id_address_start">Address start:</label>
                    <input class="form-control" type="text" name="address_start" required id="id_address_start"/>

                    <label for="id_address_end">Address end:</label>
                    <input class="form-control" type="text" name="address_end" required id="id_address_end"/>

                    <input type="hidden" name="address_start_lat" id="id_address_start_lat"/>
                    <input type="hidden" name="address_start_lng" id="id_address_start_lng"/>
                    <input type="hidden" name="address_end_lat" id="id_address_end_lat"/>
                    <input type="hidden" name="address_end_lng" id="id_address_end_lng" />
                    <input type="hidden" name="waypoints" id="id_waypoints" />

                    <button class="btn bnt-primary" type="submit">Add route</button>
                </div>
            </div>

            <div class="col-6">
                <div id="map_canvas"></div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script src="/static/django_google_maps/js/google-maps-admin.js"></script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Django Simple Login{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/django_google_maps/css/google-maps-admin.css">
    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://maps.google.com/maps/api/js?key=AIzaSyD1D8UPHkQn5H7kMOhwNRyKJt5SYrH7h64&libraries=places"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
    {% endblock %}
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">


        {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'add_routes' %}">Add routes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'view_routes' %}">View routes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'search_routes' %}">Search routes</a>
            </li>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'view_signed_routes' %}">View signed routes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Signup</a>
            </li>
        </ul>
        {% endif %}
    </nav>

</header>
<hr>
<main>
    {% block content %} {% endblock %}
</main>
<hr>
<footer>
    <a href="http://simpleisbetterthancomplex.com">simpleisbetterthancomplex.com</a>
</footer>
</body>

</html>

templates/home.html
{% extends 'base.html' %} {% block title %}Login{% endblock %} {% block content %}
{% endblock %}

templates/logged_out.html
{% extends 'base.html' %} {% block title %}See you!{% endblock %} {% block content %}
<h2>Logged out</h2>
<p>You have been successfully logged out.</p>
<p>
    <a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

templates/search_routes.html
{% extends 'base.html' %} {% block title %}Login{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-6">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_address_start">Address start:</label>
                    <input class="form-control" type="text" name="address_start" maxlength="500" required
                           id="id_address_start"/>

                    <label for="id_address_end">Address end:</label>
                    <input class="form-control" type="text" name="address_end" maxlength="500" required
                           id="id_address_end"/>

                    <label for="id_range">Range [km]:</label>
                    <input class="form-control" type="number" name="range" value="1" required
                           id="id_range"/>

                    <input type="hidden" name="address_start_lat" id="id_address_start_lat"/>
                    <input type="hidden" name="address_start_lng" id="id_address_start_lng"/>
                    <input type="hidden" name="address_end_lat" id="id_address_end_lat"/>
                    <input type="hidden" name="address_end_lng" id="id_address_end_lng"/>

                    <button class="btn bnt-primary" name="search" type="submit">Search routes</button>
                </div>
            </form>
        </div>

        <div class="col-6">
            <div id="map_canvas"></div>
        </div>
    </div>

    <div class="row">
        {% if routes %}
        <h2>Found routes:</h2>
        <table class="table table-hover table-stripped table-responsive">
            <tr>
                <th>Start adress</th>
                <th>End adress</th>
                <th>Date</th>
                <th>Hour</th>
                <th>Price</th>
                <th>Signed / Passengers</th>
            </tr>
            {% for route in routes %}
            <tr>
                <td>{{ route.address_start }}</td>
                <td>{{ route.address_end }}</td>
                <td>{{ route.date }}</td>
                <td>{{ route.hour }}</td>
                <td>{{ route.price }}</td>
                <td>{{ route.passengers_signed }} / {{ route.passengers_number }}</td>
                <td>
                    <button class="btn bnt-primary"
                            onClick="showRouteForm({{route.address_start_lat}},
                                {{route.address_start_lng}},
                                {{route.address_end_lat}},
                                {{route.address_end_lng}},
                                {{route.waypoints}})">Show
                    </button>
                </td>
                <td>
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="route_id" id="id_route_id" value="{{route.id}}"/>
                        <button class="btn bnt-primary" name="sign" type="submit">Sign for route</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>

    <div class="row">
        {% if signed_message %}
        <h4> {{ signed_message }} </h4>
        {% if route_details %}
        <table class="table table-hover table-stripped table-responsive">
            <tr>
                <th>Start adress</th>
                <th>End adress</th>
                <th>Date</th>
                <th>Hour</th>
                <th>Price</th>
            </tr>
            <tr>
                <td>{{ route_details.address_start }}</td>
                <td>{{ route_details.address_end }}</td>
                <td>{{ route_details.date }}</td>
                <td>{{ route_details.hour }}</td>
                <td>{{ route_details.price }}</td>
            </tr>
        </table>
        {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}
{% block scripts %}
{{ block.super }}
<script src="/static/django_google_maps/js/google-maps-admin.js"></script>
{% endblock %}

templates/signup.html
{% extends 'base.html' %} {% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>
{% endblock %}

templates/view_routes.html
{% extends 'base.html' %} {% block title %}Login{% endblock %}
{% block content %}
    <table class="table table-hover table-stripped table-responsive">
        <tr>
            <th>Adres początkowy</th>
            <th>Adres końcowy</th>
            <th>Data</th>
            <th>Godzina</th>
            <th>Cena</th>
        </tr>
        {% for ride in rides %}
            <tr>
                <td>{{ ride.address_start }}</td>
                <td>{{ ride.address_end }}</td>
                <td>{{ ride.date }}</td>
                <td>{{ ride.hour }}</td>
                <td>{{ ride.price }}</td>
                <td>{{ ride.id }}</td>
                <td><a href="{% url 'delete_route' ride.id %}">delete</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/view_signed_routes.html
{% extends 'base.html' %} {% block title %}Login{% endblock %}
{% block content %}
    <table class="table table-hover table-stripped table-responsive">
        <tr>
            <th>Address start</th>
            <th>Address end</th>
            <th>Date</th>
            <th>Hour</th>
            <th>Price</th>
        </tr>
        {% for ride in rides %}
            <tr>
                <td>{{ ride.address_start }}</td>
                <td>{{ ride.address_end }}</td>
                <td>{{ ride.date }}</td>
                <td>{{ ride.hour }}</td>
                <td>{{ ride.price }}</td>
                <td><a href="{% url 'sign_off_route' ride.id ride.signed_id %}">Resign from route</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}